import productsData from '../data/products.json';

export default function SpecPDFGenerator() {
    const downloadPDF = (product) => {
        // In a real app, we'd use jspdf or a backend service.
        // For this corporate demo, we'll trigger a print-friendly version of the spec.
        window.print();
    };

    return { downloadPDF };
}

// Technical Spec Template (Print Only)
export function TechSpecPrintTemplate({ product }) {
    if (!product) return null;

    return (
        <div className="hidden print:block fixed inset-0 bg-white z-[9999] p-20 text-slate-900 font-sans">
            <div className="flex justify-between items-start border-b-4 border-medical-700 pb-8 mb-12">
                <div>
                    <h1 className="text-4xl font-black uppercase tracking-tighter">TECHNICAL DATASHEET</h1>
                    <p className="text-medical-700 font-bold uppercase tracking-widest mt-2">{product.category}</p>
                </div>
                <div className="text-right">
                    <p className="font-black text-2xl uppercase">KRG MEDIFABB</p>
                    <p className="text-xs text-slate-500 uppercase">ISO 13485:2016 CERTIFIED</p>
                </div>
            </div>

            <div className="grid grid-cols-3 gap-12 mb-12">
                <div className="col-span-2">
                    <h2 className="text-2xl font-black mb-6 uppercase tracking-tight">{product.name}</h2>
                    <p className="text-slate-600 leading-relaxed mb-8">{product.description}</p>

                    <div className="grid grid-cols-2 gap-x-8 gap-y-4">
                        {[
                            { label: 'Primary Material', value: product.material },
                            { label: 'GSM Specification', value: product.gsm },
                            { label: 'Sterility Type', value: product.sterilization },
                            { label: 'Customization', value: product.customizable ? 'Available' : 'Standard Only' },
                            { label: 'MOQ Bulk Order', value: product.moq },
                            { label: 'Clinical Grade', value: 'Level 3/4 AAMI' },
                        ].map(spec => (
                            <div key={spec.label} className="border-b border-slate-100 pb-2">
                                <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">{spec.label}</p>
                                <p className="text-sm font-bold">{spec.value}</p>
                            </div>
                        ))}
                    </div>
                </div>
                <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100 h-64 flex items-center justify-center font-black text-slate-200">
                    PRODUCT IMAGE
                </div>
            </div>

            <div className="mt-24 border-t border-slate-100 pt-8">
                <h3 className="text-xs font-black uppercase tracking-widest mb-4">Compliance & Safety</h3>
                <p className="text-xs text-slate-500 max-w-2xl italic">
                    This document is generated by the KRG Medifabb B2B Procurement Portal. All data is subject to batch-wise variation in accordance with clinical standards. Scan the QR code on the physical packaging to verify batch authenticity.
                </p>
                <div className="mt-12 flex justify-between items-end">
                    <div className="p-4 bg-slate-100 rounded text-[10px] font-mono">SECURE_DOC_ID: KRG/REF/{product.id.toUpperCase()}/2026</div>
                    <p className="text-[10px] text-slate-400 uppercase">Page 1 of 1</p>
                </div>
            </div>
        </div>
    );
}
